baseURL = 'https://jonathangbrill.com/'
languageCode = 'en-us'
title = 'Jonathan G. Brill'

enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[menus]
  [[menus.main]]
    name = 'Home'
    identifier = 'home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    identifier = 'about'
    pageRef = '/about'
    weight = 20
  [[menus.main]]
    name = 'Practice Areas'
    identifier = 'practice-areas'
    pageRef = '/personal-injury'
    weight = 30
  [[menus.main]]
    name = 'Blog'
    identifier = 'blog'
    pageRef = '/blog'
    weight = 40
  [[menus.main]]
    name = 'Contact'
    identifier = 'contact'
    pageRef = '/contact'
    weight = 50
  [[menus.services]]
    name = 'Motor Vehicle Accidents'
    identifier = 'motor-vehicle-accidents'
    pageRef = '/motor-vehicle-accidents'
    weight = 100
  [[menus.services]]
    name = 'Distracted Driving Accidents'
    identifier = 'distracted-driving-accidents'
    pageRef = '/distracted-driving-accidents'
    weight = 110
  [[menus.services]]
    name = 'Workplace Accidents'
    identifier = 'workplace-accidents'
    pageRef = '/workplace-accidents'
    weight = 120
  [[menus.services]]
    name = 'Slip-and-Fall Accidents'
    identifier = 'slip-and-fall-accidents'
    pageRef = '/slip-and-fall-accidents'
    weight = 130
  [[menus.services]]
    name = 'Defective Products'
    identifier = 'defective-products'
    pageRef = '/defective-products'
    weight = 140
  [[menus.services]]
    name = 'Serious Injury'
    identifier = 'serious-injury'
    pageRef = '/serious-injury'
    weight = 150
  [[menus.services]]
    name = 'Wrongful Death'
    identifier = 'wrongful-death'
    pageRef = '/wrongful-death'
    weight = 160