backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - label: "Landing Pages"
    name: "landingPages"
    files:
      - label: "Why We Fight"
        name: "why-we-fight"
        file: "site/data/why_we_fight.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Alternate Title, name: alt_title, widget: string, required: false}
      - label: "Meet Us"
        name: "meet-us"
        file: "site/data/meet_us.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Alternate Title, name: alt_title, widget: string, required: false}
          - {label: Draft, name: draft, widget: boolean}
          - {label: Type, name: type, widget: hidden}
          - label: Sidebar Image
            name: sidebar_img
            widget: object
            fields:
              - {label: SRC, name: src, widget: image, choose_url: false, required: false}
              - {label: Alt Text, name: alt, widget: string, required: false}
          - label: Fighting for Good People
            name: fighting
            widget: object
            fields:
              - label: Image
                name: image
                widget: object
                fields:
                  - {label: SRC, name: src, widget: image, choose_url: false, required: false}
                  - {label: Alt Text, name: alt, widget: string, required: false}
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: markdown}
              - label: Call to Action
                name: cta
                widget: object
                fields:
                  - {label: Text, name: text, widget: string, required: false}
                  - {label: URL, name: url, widget: string, required: false}
          - {label: Content, name: content, widget: markdown}
  - label: "Footer"
    name: "footer"
    create: false
    editor:
      preview: false
    files:
      - label: "Footer"
        name: "footer"
        file: "data/footer.yml"
        editor:
          preview: false
        fields:
  - label: "Settings"
    name: "settings"
    create: false
    editor:
      preview: false
    files:
      - label: "Config"
        name: "config"
        file: "data/settings.yml"
        editor:
          preview: false
        fields:
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
          - { label: "Google Analytics ID", name: "google_analytics_id", widget: "string", required: false }
          - label: "Site Menu"
            name: "site_menu"
            widget: "list"
            fields:
              - { label: "Menu Item", name: "menu_item", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
            required: false
          - label: "Phone"
            name: "phone"
            widget: "string"
            required: false
          - label: "Email"
            name: "email"
            widget: "object"
            required: false
            fields:
              - { label: "Title", name: "title", widget: "string", required: false }
              - { label: "URL", name: "url", widget: "string", required: false }